In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
a.shape

(4,)

In [4]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [5]:
b.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [6]:
b.T.shape

(4, 2)

In [7]:
b.shape

(2, 4)

In [8]:
np.dot(b, b.T)

array([[ 30,  70],
       [ 70, 174]])

In [10]:
np.dot(b.T, b)

array([[26, 32, 38, 44],
       [32, 40, 48, 56],
       [38, 48, 58, 68],
       [44, 56, 68, 80]])

In [11]:
np.random.randint(60, 100, 10)

array([73, 89, 94, 93, 86, 99, 87, 62, 79, 78])

In [17]:
matrix = np.random.randint(60, 100, (5,5))
print(matrix)

[[99 89 82 84 83]
 [85 95 67 72 79]
 [84 63 94 62 88]
 [81 87 79 64 63]
 [69 62 62 92 76]]


In [18]:
print(np.min(matrix))
print(np.max(matrix))

62
99


In [19]:
a = np.array([0,1,10,10,2,-8,6,6,6,8,10])

In [20]:
np.argmin(a)

5

In [23]:
b = np.unique(a, return_counts=True)

In [24]:
idx = np.argmax(b[1])
element = b[0][idx]
print(element)

6


In [25]:
# slicing arrays

matrix

array([[99, 89, 82, 84, 83],
       [85, 95, 67, 72, 79],
       [84, 63, 94, 62, 88],
       [81, 87, 79, 64, 63],
       [69, 62, 62, 92, 76]])

In [26]:
matrix[2:4,1:3]

array([[63, 94],
       [87, 79]])