In [2]:
import pandas as pd
import numpy as np

In [8]:
d = np.random.normal(size=(2,3))
print(d)
print(type(d))

print('----------------------------------------------------')

s = pd.DataFrame(d)
print(s)
print(type(s))
print(type(pd.Series(4)))

[[-0.44395238 -1.92730318 -0.46081837]
 [-0.63241516 -0.88530918 -0.56303766]]
<class 'numpy.ndarray'>
----------------------------------------------------
          0         1         2
0 -0.443952 -1.927303 -0.460818
1 -0.632415 -0.885309 -0.563038
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [9]:
d = {
    'a' : [1,2,3,4],
    'b' : [2,4,6,8]
}

df = pd.DataFrame(d)
print(df)
print(df['a'].values)

   a  b
0  1  2
1  2  4
2  3  6
3  4  8
[1 2 3 4]


In [10]:
d = {
    "a": {
        "a1":1, 
        "a2":2, 
        "c":3
    }, 
    "b": {
        "b1":2, 
        "b2":4, 
        "c":9
    }
}
df = pd.DataFrame(d)
print("The DataFrame ")
print(df)

The DataFrame 
      a    b
a1  1.0  NaN
a2  2.0  NaN
c   3.0  9.0
b1  NaN  2.0
b2  NaN  4.0


In [11]:
s = {
    'a' : pd.Series(range(1,3)),
    'b' : pd.Series(range(2,4))
}

df = pd.DataFrame(s)
print(df)

   a  b
0  1  2
1  2  3


In [13]:
s = {
    'a' : pd.Series(range(1,3), index=['a', 'b']),
    'b' : pd.Series(range(5,7), index=['b', 'c'])
}

df = pd.DataFrame(s)
print(df)

     a    b
a  1.0  NaN
b  2.0  5.0
c  NaN  6.0


In [14]:
d = {
    "a": [1, 2, 3, 4], 
    "b": [2, 4, 6, 8]
}
df = pd.DataFrame.from_dict(d)
print("dataframe created from from_dict")
print(df)
print("--------------------")

df = pd.DataFrame.from_dict(d, orient="index")
print("dataframe created from from_dict and set the orient")
print(df)

dataframe created from from_dict
   a  b
0  1  2
1  2  4
2  3  6
3  4  8
--------------------
dataframe created from from_dict and set the orient
   0  1  2  3
a  1  2  3  4
b  2  4  6  8


In [15]:
df = pd.read_csv('sample.csv', sep=',')
print(df.head(1))

     animal  uniq_id  water_need
0  elephant     1001         500


In [16]:
df = pd.read_csv('sample.csv', sep=',', nrows=10)
print(df.shape)
print(df.shape[0])

(10, 3)
10


In [18]:
df = pd.read_csv('sample.csv', sep=',', header=None, names=['a', 'b', 'c'])
print(df.head(1))

        a        b           c
0  animal  uniq_id  water_need


In [22]:
df = pd.read_csv('sample.csv', sep=',', header=0, usecols=['animal'])
print(df.head())

     animal
0  elephant
1  elephant
2  elephant
3     tiger
4     tiger
