In [3]:
import pandas as pd

In [9]:
l = range(1,10)
print(type(l))
print(isinstance(l, range))
s = pd.Series(l)
print(type(s))
print(s)
print('-----------------')
x = 3
print('the index {} -> value is {}'.format(x, s[x]))
print(f'the index {x} -> value is {s[x]}')

<class 'range'>
True
<class 'pandas.core.series.Series'>
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64
-----------------
the index 3 -> value is 4
the index 3 -> value is 4


In [11]:
r2 = range(1,6)
idx = ['aa', 'bb', 'ccc', 'dddd', 'eeeee']
s2 = pd.Series(r2, idx)
print(s2)
print(s2['ccc'])

aa       1
bb       2
ccc      3
dddd     4
eeeee    5
dtype: int64
3


In [14]:
dic = {
    'bb' : 1,
    'a' : 0,
    'ccc' : 2
}

s = pd.Series(dic)
print(s)
print(s['ccc'])

bb     1
a      0
ccc    2
dtype: int64
2


In [15]:
import numpy as np

In [18]:
l = np.arange(1,10, 2)
print(type(l))
print('-----------------')
s = pd.Series(l)
print(s)
print(s[3])

<class 'numpy.ndarray'>
-----------------
0    1
1    3
2    5
3    7
4    9
dtype: int64
7


In [19]:
s = pd.Series(3)
print(s)
print('---------------')
s = pd.Series(3, index = range(1,4))
print(s)

0    3
dtype: int64
---------------
1    3
2    3
3    3
dtype: int64


In [20]:
s = pd.Series(range(1,20))

In [21]:
print(s[1])

2


In [24]:
print(s[[1,5]])

1    2
5    6
dtype: int64


In [25]:
print(s[5:])

5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
dtype: int64


In [26]:
print(s[1:10:2])

1     2
3     4
5     6
7     8
9    10
dtype: int64


In [27]:
s = pd.Series(range(1,20))

In [30]:
s1 = s[s%2==0]
print(type(s1))
print(s1.values)

<class 'pandas.core.series.Series'>
[ 2  4  6  8 10 12 14 16 18]


In [31]:
s2 = s[s>8]
print(s2.values)

[ 9 10 11 12 13 14 15 16 17 18 19]


In [32]:
s3 = s[s > s.mean()]
print(s3.values)

[11 12 13 14 15 16 17 18 19]


In [34]:
s = pd.Series(range(1,8))
d1 = s * 2
print(s.values, d1.values)

[1 2 3 4 5 6 7] [ 2  4  6  8 10 12 14]


In [35]:
d2 = s + s + s
print(s.values, d2.values)

[1 2 3 4 5 6 7] [ 3  6  9 12 15 18 21]


In [36]:
d4 = np.sin(s)
print(s.values, d4.values)

[1 2 3 4 5 6 7] [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866 ]
